// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.GameCode.Templates
{
    using Schema;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class StructTemplate : StructTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 1 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\GeneratedCodeWarning.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("//-------------------------------------------------------------------------------"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 2 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\GeneratedCodeWarning.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("//                                                                               "));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 3 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\GeneratedCodeWarning.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("//    This code was automatically generated.                                     "));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 4 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\GeneratedCodeWarning.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("//    Changes to this file may cause incorrect behavior and will be lost if      "));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 5 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\GeneratedCodeWarning.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("//    the code is regenerated.                                                   "));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 6 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\GeneratedCodeWarning.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("//                                                                               "));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 7 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\GeneratedCodeWarning.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture("//-------------------------------------------------------------------------------"));
            
            #line default
            #line hidden
            this.Write("\r\n");
            this.Write("\r\nusing System.Collections.Generic;\r\nusing ");
            
            #line 9 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.RootNamespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 9 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.UtilsNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 11 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.RootNamespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 11 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Context.GetObjectNamespace(ObjectData.name)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic readonly partial struct ");
            
            #line 13 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.name));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n");
            
            #line 15 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"

		PushIndent("\t\t");
		foreach (var item in ObjectData.members)
			WriteClassMember(item, Context, true);
		PopIndent();

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 22 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 22 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.CallbackInterface));
            
            #line default
            #line hidden
            this.Write(" parent)\r\n\t\t{\r\n");
            
            #line 24 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"

			PushIndent("\t\t\t");
			foreach (var item in ObjectData.members)
				WriteInitializer(item, Context, "parent");
			PopIndent();

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\tpublic ");
            
            #line 32 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 32 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.ReaderClass));
            
            #line default
            #line hidden
            this.Write(" reader, ");
            
            #line 32 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.CallbackInterface));
            
            #line default
            #line hidden
            this.Write(" parent)\r\n\t\t{\r\n");
            
            #line 34 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"

			PushIndent("\t\t\t");
			foreach (var item in ObjectData.members)
				WriteDeserializationCode(item, Context, "parent");
			PopIndent();

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n");
            
            #line 42 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"

		PushIndent("\t\t");
		foreach (var item in ObjectData.members)
			WriteProperty(item, Context, true);
		PopIndent();

		if (Context.IsLatestObjectVersion(ObjectData.name))
		{

            
            #line default
            #line hidden
            this.Write("\r\n        public void Serialize(");
            
            #line 52 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.WriterClass));
            
            #line default
            #line hidden
            this.Write(" writer)\r\n        {\r\n");
            
            #line 54 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"

			PushIndent("\t\t\t");
			foreach (var item in ObjectData.members)
				WriteSerializationCode(item, Context);
			PopIndent();

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public bool Equals(");
            
            #line 62 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.name));
            
            #line default
            #line hidden
            this.Write(" other)\r\n        {\r\n");
            
            #line 64 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"

    		PushIndent("\t\t\t");
    		foreach (var item in ObjectData.members)
	    		WriteComparisonCode(item, Context);
    		PopIndent();

            
            #line default
            #line hidden
            this.Write("            return true;\r\n        }\r\n\r\n        public struct EqualityComparer : I" +
                    "EqualityComparer<");
            
            #line 73 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.name));
            
            #line default
            #line hidden
            this.Write(">\r\n        {\r\n            public bool Equals(");
            
            #line 75 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.name));
            
            #line default
            #line hidden
            this.Write(" first, ");
            
            #line 75 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.name));
            
            #line default
            #line hidden
            this.Write(" second) => first.Equals(second);\r\n            public int GetHashCode(");
            
            #line 76 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ObjectData.name));
            
            #line default
            #line hidden
            this.Write(" obj) => obj.GetHashCode();\r\n        }\r\n");
            
            #line 78 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\StructTemplate.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 2 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\UtilsClassMember.tt"


private string ConvertType(string type, SchemaVersionInfo context)
{
	if (type == Constants.TypeInt)
	{
		return "int";
	}
	else if (type == Constants.TypeUint)
	{
		return "uint";
	}
	else if (type == Constants.TypeLong)
	{
		return "long";
	}
	else if (type == Constants.TypeUlong)
	{
		return "ulong";
	}
	else if (type == Constants.TypeShort)
	{
		return "short";
	}
	else if (type == Constants.TypeUshort)
	{
		return "ushort";
	}
	else if (type == Constants.TypeSbyte)
	{
		return "sbyte";
	}
	else if (type == Constants.TypeByte)
	{
		return "byte";
	}
	else if (type == Constants.TypeFloat)
	{
		return "float";
	}
	else if (type == Constants.TypeBool)
	{
		return "bool";
	}
	else if (type == Constants.TypeString)
	{
		return "string";
	}
	else if (type == Constants.TypeBitset)
	{
		return Utils.BitsetType;
	}
	else if (context.HasClass(type))
	{
		return context.GetObjectName(type);
	}
	else if (context.HasStruct(type))
	{
		return context.GetObjectName(type);
	}
	else
	{
		throw new InvalidSchemaException("Invalid type - " + type);
	}
}

private void WriteProperty(XmlClassMember member, SchemaVersionInfo context, bool readOnly)
{
	var propertyName = Utils.PropertyName(member.name);
	var memberName = Utils.PrivateMemberName(member.name);
	var notify = !member.options.Contains(Constants.OptionNotImportant);

	if (member.type == Constants.TypeMap)
	{
		WriteLine($"public {Utils.MapType}<{ConvertType(member.key, context)}, {ConvertType(member.value, context)}> {propertyName} => {memberName};");
	}
	else if (member.type == Constants.TypeSet)
	{
		WriteLine($"public {Utils.SetType}<{ConvertType(member.value, context)}> {propertyName} => {memberName};");
	}
	else if (member.type == Constants.TypeList)
	{
		WriteLine($"public {Utils.ListType}<{ConvertType(member.value, context)}> {propertyName} => {memberName};");
	}
	else if (member.type == Constants.TypeBitset)
	{
		WriteLine($"public {Utils.BitsetType} {propertyName} => {memberName};");
	}
	else if (member.type == Constants.TypeInventory)
	{
		WriteLine($"public {Utils.InventoryType}<{ConvertType(member.value, context)}> {propertyName} => {memberName};");
	}
	else if (readOnly)
	{
		WriteLine($"public {ConvertType(member.type, context)} {propertyName} => {memberName};");
	}
	else
	{
		WriteLine($"public {ConvertType(member.type, context)} {propertyName}");
		WriteLine("{");
		PushIndent("\t");
		WriteLine($"get => {memberName};");
		WriteLine("set");
		WriteLine("{");
		PushIndent("\t");
		WriteLine($"if ({memberName} == value) return;");
		WriteLine($"{memberName} = value;");
		if (context.HasClass(member.type)) WriteLine($"{memberName}.Parent = this;");
		if (notify) WriteLine(Utils.CallbackMethod + "();");
		PopIndent();
		WriteLine("}");
		PopIndent();
		WriteLine("}");
	}
}

private void WriteInitializer(XmlClassMember member, SchemaVersionInfo context, string callback)
{
	var memberName = Utils.PrivateMemberName(member.name);

	if (member.type == Constants.TypeMap)
	{
		WriteLine($"{memberName} = new {Utils.MapType}<{ConvertType(member.key, context)}, {ConvertType(member.value, context)}>({callback});");
	}
	else if (member.type == Constants.TypeSet)
	{
		WriteLine($"{memberName} = new {Utils.SetType}<{ConvertType(member.value, context)}>({callback});");
	}
	else if (member.type == Constants.TypeList)
	{
		WriteLine($"{memberName} = new {Utils.ListType}<{ConvertType(member.value, context)}>({callback});");
	}
	else if (member.type == Constants.TypeBitset)
	{
		WriteLine($"{memberName} = new {Utils.BitsetType}({callback});");
	}
	else if (member.type == Constants.TypeInventory)
	{
		WriteLine($"{memberName} = new {Utils.InventoryType}<{ConvertType(member.value, context)}>({callback});");
	}
	else if (context.HasClass(member.type))
	{
		WriteLine($"{memberName} = new {ConvertType(member.type, context)}({callback});");
	}
	else if (context.HasStruct(member.type))
	{
		WriteLine($"{memberName} = new {ConvertType(member.type, context)}({callback});");
	}
	else
	{
		WriteLine($"{memberName} = {GetDefaultValue(member.@default, member.type, context)};");
	}
}

private string GetDefaultValue(string value, string type, SchemaVersionInfo context)
{
	if (type == Constants.TypeString)
		return string.IsNullOrEmpty(value) ? "string.Empty" : $"\"{value}\"";

	if (string.IsNullOrEmpty(value))
		return $"default({ConvertType(type, context)})";

	if (value == Constants.Timestamp)
		return $"({ConvertType(type, context)})System.DateTime.UtcNow.Ticks";

	return value;
}

private void WriteClassMember(XmlClassMember member, SchemaVersionInfo context, bool readOnly)
{
	var memberName = Utils.PrivateMemberName(member.name);
	var encrypted = member.options.Contains(Constants.OptionEncrypted);
	var prefix = readOnly ? "private readonly " : "private ";
	var suffix = ";";

	string memberType;
	if (member.type == Constants.TypeMap)
	{
		memberType = $"{Utils.MapType}<{ConvertType(member.key, context)}, {ConvertType(member.value, context)}>";
	}
	else if (member.type == Constants.TypeSet)
	{
		memberType = $"{Utils.SetType}<{ConvertType(member.value, context)}>";
	}
	else if (member.type == Constants.TypeList)
	{
		memberType = $"{Utils.ListType}<{ConvertType(member.value, context)}>";
	}
	else if (member.type == Constants.TypeBitset)
	{
		memberType = $"{Utils.BitsetType}";
	}
	else if (member.type == Constants.TypeInventory)
	{
		memberType = $"{Utils.InventoryType}<{ConvertType(member.value, context)}>";
	}
	else if (encrypted)
	{
		if (member.type == Constants.TypeInt)
			memberType = Utils.EncryptedIntType;
		else if (member.type == Constants.TypeLong)
			memberType = Utils.EncryptedLongType;
		else
			throw new System.InvalidOperationException($"'encrypted' not supported for type {member.type}");
	}
	else
	{
		memberType = ConvertType(member.type, context);
	}

	WriteLine(prefix + memberType + " " + memberName + suffix);
}


        
        #line default
        #line hidden
        
        #line 2 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\UtilsSerializationCode.tt"


private void WriteSerializationCode(XmlClassMember member, SchemaVersionInfo context)
{
	var memberName = Utils.PrivateMemberName(member.name);
	var encoding = Utils.GetEncodingType(member.encoding);

	if (member.type == Constants.TypeList)
	{
		WriteSerializationCode($"{memberName}.Count", Constants.TypeInt, context, encoding);
		WriteLine($"for (int i = 0; i < {memberName}.Count; ++i)");
		WriteLine("{");
		PushIndent("\t");
		WriteSerializationCode($"{memberName}[i]", member.value, context, encoding);
		PopIndent();
		WriteLine("}");
	}
	else if (member.type == Constants.TypeMap)
	{
		WriteSerializationCode($"{memberName}.Count", Constants.TypeInt, context, encoding);
		WriteLine($"foreach (var item in {memberName})");
		WriteLine("{");
		PushIndent("\t");
		WriteSerializationCode("item.Key", member.key, context, encoding);
		WriteSerializationCode("item.Value", member.value, context, encoding);
		PopIndent();
		WriteLine("}");
	}
	else if (member.type == Constants.TypeInventory)
	{
		WriteSerializationCode($"{memberName}.Count", Constants.TypeInt, context, encoding);
		WriteLine($"foreach (var item in {memberName})");
		WriteLine("{");
		PushIndent("\t");
		WriteSerializationCode("item.Key", member.value, context, encoding);
		WriteSerializationCode("item.Value", Constants.TypeInt, context, encoding);
		PopIndent();
		WriteLine("}");
	}
	else if (member.type == Constants.TypeSet)
	{
		WriteSerializationCode($"{memberName}.Count", Constants.TypeInt, context, encoding);
		WriteLine($"foreach (var item in {memberName})");
		WriteLine("{");
		PushIndent("\t");
		WriteSerializationCode("item", member.value, context, encoding);
		PopIndent();
		WriteLine("}");
	}
	else
	{
		WriteSerializationCode(memberName, member.type, context, encoding);
	}
}

private void WriteSerializationCode(string memberName, string memberType, SchemaVersionInfo context, string encoding)
{
	if (memberType == Constants.TypeInt)
		WriteLine($"writer.WriteInt({memberName}, {encoding});");
	else if (memberType == Constants.TypeUint)
		WriteLine($"writer.WriteUint({memberName}, {encoding});");
	else if (memberType == Constants.TypeLong)
		WriteLine($"writer.WriteLong({memberName}, {encoding});");
	else if (memberType == Constants.TypeUlong)
		WriteLine($"writer.WriteUlong({memberName}, {encoding});");
	else if (memberType == Constants.TypeShort)
		WriteLine($"writer.WriteShort({memberName}, {encoding});");
	else if (memberType == Constants.TypeUshort)
		WriteLine($"writer.WriteUshort({memberName}, {encoding});");
	else if (memberType == Constants.TypeSbyte)
		WriteLine($"writer.WriteSbyte({memberName}, {encoding});");
	else if (memberType == Constants.TypeByte)
		WriteLine($"writer.WriteByte({memberName}, {encoding});");
	else if (memberType == Constants.TypeFloat)
		WriteLine($"writer.WriteFloat({memberName}, {encoding});");
	else if (memberType == Constants.TypeBool)
		WriteLine($"writer.WriteBool({memberName}, {encoding});");
	else if (memberType == Constants.TypeString)
		WriteLine($"writer.WriteString({memberName}, {encoding});");
	else if (memberType == Constants.TypeBitset)
		WriteLine($"{memberName}.Serialize(writer, {encoding});");
	else
		WriteLine($"{memberName}.Serialize(writer);");
}


        
        #line default
        #line hidden
        
        #line 2 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\UtilsDeserializationCode.tt"


private void WriteDeserializationCode(XmlClassMember member, SchemaVersionInfo context, string callback)
{
	var memberName = Utils.PrivateMemberName(member.name);
	var encoding = Utils.GetEncodingType(member.encoding);

	if (member.type == Constants.TypeList)
	{
		var count = Utils.LocalVariableName(member.name) + "ItemCount";
		WriteLine($"int {count};");
		WriteDeserializationCode(count, Constants.TypeInt, context, callback, encoding);
		WriteLine($"{memberName} = new {Utils.ListType}<{ConvertType(member.value, context)}>({count}, {callback});");
		WriteLine($"for (int i = 0; i < {count}; ++i)");
		WriteLine("{");
		PushIndent("\t");
		WriteLine($"{ConvertType(member.value, context)} item;");
		WriteDeserializationCode($"item", member.value, context, callback, encoding);
		WriteLine($"{memberName}.Add(item);");
		PopIndent();
		WriteLine("}");
	}
	else if (member.type == Constants.TypeMap)
	{
		var count = Utils.LocalVariableName(member.name) + "ItemCount";
		WriteLine($"int {count};");
		WriteDeserializationCode(count, Constants.TypeInt, context, callback, encoding);
		WriteLine($"{memberName} = new {Utils.MapType}<{ConvertType(member.key, context)}, {ConvertType(member.value, context)}>({callback});");
		WriteLine($"for (int i = 0; i < {count}; ++i)");
		WriteLine("{");
		PushIndent("\t");
		WriteLine($"{ConvertType(member.key, context)} key;");
		WriteLine($"{ConvertType(member.value, context)} value;");
		WriteDeserializationCode("key", member.key, context, callback, encoding);
		WriteDeserializationCode("value", member.value, context, callback, encoding);
		WriteLine($"{memberName}.Add(key,value);");
		PopIndent();
		WriteLine("}");
	}
	else if (member.type == Constants.TypeInventory)
	{
		var count = Utils.LocalVariableName(member.name) + "ItemCount";
		WriteLine($"int {count};");
		WriteDeserializationCode(count, Constants.TypeInt, context, callback, encoding);
		WriteLine($"{memberName} = new {Utils.InventoryType}<{ConvertType(member.value, context)}>({callback});");
		WriteLine($"for (int i = 0; i < {count}; ++i)");
		WriteLine("{");
		PushIndent("\t");
		WriteLine($"{ConvertType(member.value, context)} value;");
		WriteLine($"int quantity;");
		WriteDeserializationCode("value", member.value, context, callback, encoding);
		WriteDeserializationCode("quantity", Constants.TypeInt, context, callback, encoding);
		WriteLine($"{memberName}.Add(value,quantity);");
		PopIndent();
		WriteLine("}");
	}
	else if (member.type == Constants.TypeSet)
	{
		var count = Utils.LocalVariableName(member.name) + "ItemCount";
		WriteLine($"int {count};");
		WriteDeserializationCode(count, Constants.TypeInt, context, callback, encoding);
		WriteLine($"{memberName} = new {Utils.SetType}<{ConvertType(member.value, context)}>({callback});");
		WriteLine($"for (int i = 0; i < {count}; ++i)");
		WriteLine("{");
		PushIndent("\t");
		WriteLine($"{ConvertType(member.value, context)} item;");
		WriteDeserializationCode("item", member.value, context, callback, encoding);
		WriteLine($"{memberName}.Add(item);");
		PopIndent();
		WriteLine("}");
	}
	else
	{
		WriteDeserializationCode(memberName, member.type, context, callback, encoding);
	}
}

private void WriteDeserializationCode(string memberName, string memberType, SchemaVersionInfo context, string callback, string encoding)
{
	if (memberType == Constants.TypeInt)
		WriteLine($"{memberName} = reader.ReadInt({encoding});");
	else if (memberType == Constants.TypeUint)
		WriteLine($"{memberName} = reader.ReadUint({encoding});");
	else if (memberType == Constants.TypeLong)
		WriteLine($"{memberName} = reader.ReadLong({encoding});");
	else if (memberType == Constants.TypeUlong)
		WriteLine($"{memberName} = reader.ReadUlong({encoding});");
	else if (memberType == Constants.TypeShort)
		WriteLine($"{memberName} = reader.ReadShort({encoding});"); 
	else if (memberType == Constants.TypeUshort)
		WriteLine($"{memberName} = reader.ReadUshort({encoding});"); 
	else if (memberType == Constants.TypeSbyte)
		WriteLine($"{memberName} = reader.ReadSbyte({encoding});"); 
	else if (memberType == Constants.TypeByte)
		WriteLine($"{memberName} = reader.ReadByte({encoding});"); 
	else if (memberType == Constants.TypeFloat)
		WriteLine($"{memberName} = reader.ReadFloat({encoding});"); 
	else if (memberType == Constants.TypeBool)
		WriteLine($"{memberName} = reader.ReadBool({encoding});"); 
	else if (memberType == Constants.TypeString)
		WriteLine($"{memberName} = reader.ReadString({encoding});"); 
	else if (memberType == Constants.TypeBitset)
		WriteLine($"{memberName} = new {ConvertType(memberType, context)}(reader, {encoding}, {callback});");
	else
		WriteLine($"{memberName} = new {ConvertType(memberType, context)}(reader, {callback});");
}


        
        #line default
        #line hidden
        
        #line 2 "D:\Projects\event-horizon-main\Assets\Modules\GameSession\.CodeGenerator\CodeGenerator\GameCode\Templates\UtilsComparisonCode.tt"


private string GetEqualityComparer(string type, SchemaVersionInfo context)
{
	if (type == Constants.TypeInt)
	{
		return "EqualityComparer<int>.Default";
	}
	else if (type == Constants.TypeUint)
	{
		return "EqualityComparer<uint>.Default";
	}
	else if (type == Constants.TypeLong)
	{
		return "EqualityComparer<long>.Default";
	}
	else if (type == Constants.TypeUlong)
	{
		return "EqualityComparer<ulong>.Default";
	}
	else if (type == Constants.TypeShort)
	{
		return "EqualityComparer<short>.Default";
	}
	else if (type == Constants.TypeUshort)
	{
		return "EqualityComparer<ushort>.Default";
	}
	else if (type == Constants.TypeSbyte)
	{
		return "EqualityComparer<sbyte>.Default";
	}
	else if (type == Constants.TypeByte)
	{
		return "EqualityComparer<byte>.Default";
	}
	else if (type == Constants.TypeFloat)
	{
		return "EqualityComparer<float>.Default";
	}
	else if (type == Constants.TypeBool)
	{
		return "EqualityComparer<bool>.Default";
	}
	else if (type == Constants.TypeString)
	{
		return "System.StringComparer.Ordinal";
	}
	else if (context.HasStruct(type))
	{
		return $"new {ConvertType(type, context)}.EqualityComparer()";
	}
	else
	{
		throw new InvalidSchemaException("Invalid type - " + type);
	}
}

private void WriteComparisonCode(XmlClassMember member, SchemaVersionInfo context)
{
	var propertyName = Utils.PropertyName(member.name);

	if (member.type == Constants.TypeMap || member.type == Constants.TypeSet || member.type == Constants.TypeList)
	{
		WriteLine($"if (!{propertyName}.Equals(other.{propertyName}, {GetEqualityComparer(member.value, context)})) return false;");
	}
	else if (member.type == Constants.TypeBitset || member.type == Constants.TypeInventory || context.HasStruct(member.type))
	{
		WriteLine($"if (!{propertyName}.Equals(other.{propertyName})) return false;");
	}
	else
	{
		WriteLine($"if ({propertyName} != other.{propertyName}) return false;");
	}
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class StructTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
