using GameDatabase.Model;
using UnityEngine;

namespace Combat.Component.Bullet.SpawnSettings
{
    /// <summary>
    /// Wrapper to add extra offset or rotation to the values generated by the underlying IBulletSpawnSettings
    /// </summary>
    public class BulletSpawnSettingsWrapper : IBulletSpawnSettings
    {
        public BulletSpawnSettingsWrapper(IBulletSpawnSettings parent, Vector2 offset, float rotation)
        {
            _parent = parent;
            _offset = offset;
            _rotation = rotation;
        }

        public Vector2 GetOffset(int bulletIndex)
        {
            return _parent.GetOffset(bulletIndex) + _offset;
        }

        public float GetRotation(int bulletIndex)
        {
            return _parent.GetRotation(bulletIndex) + _rotation;
        }

        private readonly IBulletSpawnSettings _parent;
        private readonly Vector2 _offset;
        private readonly float _rotation;
    }
}